<?php $lang['a classsnapshots mask0x250 fancybox hrefwwwrootimagessitestaresearchandroidappsmusicgamesjpg datafancyboxgrouptrackauthority                             img srcwwwrootimagessitestaresearchandroidappsmusicgames400x0jpg                             div classblackoutfadebgdiv                        a'] = '<ul class=\'competitorlist\'>
<li><a href="http://www.pandora.com" target="_blank">Pandora.com</a> Gratis, $39/año sin publicidad</li>

<li><a href="http://www.spotify.com" target="_blank">Spotify.com</a> Gratis, $5/mes sin publicidad, $10/mes sin publicidad con acceso móvil sin conexion de su red</li>
</ul> 

<a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ta/research/android-apps-music-games.jpg" data-fancybox-group="trackauthority" >
<img src="/wwwroot/images/sites/ta/research/android-apps-music-games_400x0.jpg" />
<div class="blackOutFadeBG"></div>
</a>

<a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ta/research/vivetuboleta.jpg" data-fancybox-group="trackauthority" >
<img src="/wwwroot/images/sites/ta/research/vivetuboleta_400x0.jpg" />
<div class="blackOutFadeBG"></div>
</a>

<a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ta/research/ticket-express.jpg" data-fancybox-group="trackauthority" >
<img src="/wwwroot/images/sites/ta/research/ticket-express_400x0.jpg" />
<div class="blackOutFadeBG"></div>
</a>

<a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ta/research/entradas-y-conciertos.jpg" data-fancybox-group="trackauthority" >
<img src="/wwwroot/images/sites/ta/research/entradas-y-conciertos_400x0.jpg" />
<div class="blackOutFadeBG"></div>
</a>'; $lang['ema platform for high school newspapers that allows students to collaborate and share their academic and athletic achievementsem                pstudents and teachers would be able to develop assignments work on multiple versions of a story share ideas within the class and morep                            pthe competitive advantage of this site is in the versioncontrolling system that allows peerreviews teachers edit and the students versions to all be tracked independently in addition the system would include tools for simplifying footnotes and sources and to include photos and linksp'] = '<em>Es una plataforma para periódicos escolares que permite a los estudiantes colaborar y compartir sus logros académicos y deportivos.</em>

<p>Los estudiantes y los profesores podrán desarrollar tareas, escribir  historias con múltiplex versiones y compartir ideas dentro de la clase, entre otras cosas.</p>            

<p>La ventaja competitiva de este sitio se encuentra en el sistema que permite recibir comentarios y correcciones  de los profesores  hacia los estudiantes, quienes podrán revisarlos de manera independiente. Además, los profesores podrán escribir comentarios y calificar los reportes con un iPad y lápiz</p>'; $lang['ema virtual marketplace for independent retailers to publish and track promotions along with their returnoninvestment roiem                    pcustomers can search promotions and publish their own requests to nearby retailers for special deals the marketplace is focused on private offers only valid for a few hoursp'] = '<em>Un mercado virtual que permite que las empresas independientes puedan publicar  sus promociones y hacerles seguimiento.</em>

<p>A través de esta aplicación podrás saber cuánto dinero ahorras cuando logras aprovechar las promociones. Además los clientes pueden buscar ofertas y  también publicar sobre lo que necesitan. El mercado se centra en ofertas privadas válidas sólo por pocas horas.</p>'; $lang['eman etextbook for the legal and strategical aspects of the music recording industryem                      pthe tool would guide and prepare artists concert promoters event venues and talent managers through business and contract negotiations for a wide variety of agreements p                      pthe interactive questionnaire would include videos podcasts and written advice from experienced prominent attorneys artists managers and other industry professionalsp'] = '<em>Un libro electrónico  que trata los  aspectos jurídicos y estratégicos de la Industria Discográfica.</em>
<p>Esta herramienta podrá orientar y preparar a los artistas, promotores de conciertos y gerentes de talento sobre cómo hacer negociaciones comerciales y contractuales dentro de una amplia variedad de acuerdos.</p>
<p>El cuestionario interactivo incluye vídeos, podcasts y consejos  de  abogados, artistas, administradores y otros profesionales experimentados de la industria.</p>'; $lang['eman online and mobile game for music lovers to play exchange and reward musical tasteem                    phighly rated users are rewarded with free music gift certificates concert tickets and cash from sponsors and partnersp                    pthe platform supports three ways to play and win each starts with a playlist theme such as rise and shine songs for my alarm clockp                    ul                        li1 group members enter a song that suits the themeli                        li2 group members list and rate each others songsli                        li3 after two weeks the person who submitted the highest rated song winsli                    ul                    pthis game can easily be incorporated as a promotional vehicle for concert tours for example if that alarm clock was jayzs the options are countless for prizes from tickets to backstage passes and all links during the competition promote the concertp'] = '<em>Es un juego en línea y para teléfonos móviles que permite a los amantes de la música poder reproducir e intercambiar canciones y obtener recompensas por su gusto musical.</em>

<p>Los usuarios podrán ser calificados y quienes registren las más altas calificaciones serán premiados con música gratis, bonos de regalos, entradas para conciertos y  los más afortunados con dinero en efectivo. Todo esto auspiciado por los  patrocinadores y socios.</p>

<p>La plataforma soporta tres formas de jugar y ganar. Cada una comienza con un tema de una lista de reproducción y las tres permiten promover artistas, vídeos de música y giras de conciertos.</p>'; $lang['emthe first mobile beat machine to create and share music with friends in realtimeem                     plike most similar apps studioenvivo allows customizing your keyboard with sounds and laying background tracks as you playp                    phowever unlike any other app you can play simultaneously with other friends via bluetooth  chord  allshare frameworks and finally stitch together your recordings for a collaborative compositionp                    pas users upload their compositions to the cloud the social aspect of sharing and comparing compositions are endlessp'] = '<em>La primera máquina de ritmo para crear y compartir música  en tiempo real con distintos amigos y a través del teléfono móvil.</em> 
<p>StudioEnVivo te permite jugar personalizando tu teclado con sonidos, mientras escuchas una canción de fondo.</p>

<p>Sin embargo, la diferencia con otras aplicaciones es que en esta puedes jugar con otros amigos y compartir lo que haces a través de Bluetooth / Chord/ All-Share. Finalmente podrás fusionar las grabaciones para lograr una composición única.</p>

<p>Los usuarios pueden subir sus creaciones a la  red, compartirlas y comparar composiciones infinitas.</p>'; $lang['peli founded taylor made management in 2002 to produce a public music amp arts festival called a hrefprojectspid7 targetblanktraffica this url was the a hrefhttptraffictaylormadetrafficcomtraffichtml targetblankwebsitea today it is a portfolio of the projects he has been blessed to be part of and the many a hrefteampeoplea who have contributedppthis page features the products and brands directly from taylormadetraffic we are seeking likeminded visionaries that know how to develop design or sell if thats you please reach out span classalinktmttaylormadetrafficcomspanppif you have your own product that you are passionate about and feel i might be of service please do the same or use the filters above to find similar work experiences by a hreftechnologiestechnologya or a hrefindustriesindustryap'] = '<p>Eli estableció Taylor Made Management en 2002 para producir un festival público de la música y las artes llamado <a href=\'/projects?pid=7\' target=\'_blank\'>Traffic</a>. Esta URL estuvó la <a href=\'http://traffic.taylormadetraffic.com/traffic.html\' target=\'_blank\'>página web</a>. Hoy esta una cartera de los proyectos que ha tenido la suerte para contribir y de los compañeros que han contribuido.</p>

<p>Esta página presenta los productos propios de TaylorMadeTraffic. Estamos buscando por visionarios de la misma pasión quien saben cómo desarrollar, diseñar o vender. Si ése es usted, por favor acercarse.</p>

<p>Si usted tiene su propio producto que te apasiona, y siente que yo podría servir, por favor, hacer lo mismo o usan los filtros para encontrar experiencias similares en tecnología o la industria.</p>'; $lang['pi am searching for the perfect international team to share these vision and expand the business if you are interested in a product from one of these short summaries please request the complete media kit and business plan each has a much more indepth analysis of the target market industry competitors technical hurdles and profitable opportunitiesp'] = '<p>Quiero reunir un equipo internacional y competente para compartir la visión y ampliar el negocio. Esta página sólo muestra resúmenes  cortos de cinco ideas. Si quieren más información, envíeme un correo para solicitar un plan de negocios completo, con un análisis más detallado del mercado y los objetivos, la competencia en la industria, obstáculos técnicos y, finalmente, las oportunidades más rentables.</p>'; $lang['pi have a passion for music art culture and education to diversify my exposure and knowledge of those subjects i live between san francisco california bogot colombia and the hawaiian island of kauaippcombined with skills in an array of computer technologies as well as broad experiences in business development my focus is helping companies develop their own systems and finding strategies for expansion throughout south americappwhere ever you are in the world if you have a product you are also passionate about and feel i could be of service i love a good excuse to travel and will generally assume the cost for serious inquiries to do so i am always available via email span classalinkeattaylormadetrafficcomspan google voice span classalink14153000834span or skype span classalinkskyeelispanp'] = '<p>Tengo una pasión por la música, el arte, la cultura y la educación. Para diversificar mi exposición y conocimientos de estos, yo vivo entre San Francisco, California, Bogotá, Colombia, y la isla Hawaiana de Kauai.</p> 

<p>En combinación con habilidades en una serie de tecnologías, y experiencias amplias en el desarrollo de negocios, mi objetivo es ayudar a las empresas a desarrollar sus propios sistemas y la búsqueda de estrategias de expansión en toda Sur / Centro América.</p>

<p>Donde quiera que usted se encuentre en el mundo, si tiene un producto por el cual está apasionado y siente que yo pueda ser de servicio, sería una buena excusa para viajar porque me enacanta y yo asumiría los costos. Por eso, estoy siempre disponible a través de correo electrónico: <span class=\'alink\'>eli@taylormadetraffic.com</span>, google voice: <span class=\'alink\'>1-415-300-0834</span> o, skype: <span class=\'alink\'>skye_eli</span></p>'; $lang['ul classalphalist                            li1 download adfree versionli                            li5 download adfree with offline access and cloud storageli                        ul'] = '<ul class=\'alphalist\'>
                            <li>$1 descargar versión sin publicidad</li>
                            <li>$5 descargar sin publicidad con acceso sin conexión móvil y almacenamiento en la nube</li>
                        </ul>'; $lang['ul classalphalist                            li1month for store owners to view customers data and analyticsli                            li1month for store owners to send 100 private discount offers per monthli                            li1month for store owners to public 10 public market ads per monthli                            lidesign amp development services for more engaging mobile ads and promotionsli                            libuild interactive and engaging maps for mallsli                        ul'] = '<ul class=\'alphalist\'>
                            <li>$ 1/mes para los propietarios de tiendas para ver datos y análisis de los clientes</li>
                            <li>$ 1/mes para los propietarios de tiendas para enviar 100 de descuento privada ofrece al mes</li>
                            <li>$ 1/mes para los propietarios de tiendas a 10 anuncios públicos en el mercado público al mes</li>
                            <li>Diseño y Desarrollo de servicios para los anuncios para móviles atractivos más y promociones</li>
                            <li>Construir mapas interactivos y atractivos para los centros comerciales</li>
                        </ul>'; $lang['ul classalphalist                            li50 textbook sold through music and law institutions and universitiesli                            li10  50 online subscriptionsli                        ul'] = '<ul class=\'alphalist\'>
                            <li>$50 libro vendido a través de instituciones de música y universidades con facultades de Derecho</li>
                            <li>$10 - $50 USD suscripciones online.</li>
                        </ul>'; $lang['ul classalphalist                            liconcert ticket resales 35 feeli                            li1  10 subscriptions to adfree listening and extra playlist featuresli                            liconcert ticket promotions advertising and salesli                        ul'] = '<ul class=\'alphalist\'> 
<li> reventas de boletas para conciertos (tasa del 3-5%) </li> 
<li> $1 - $10 suscripciones sin publicidad y capacidad para personalizar listas de reproducciónes</ li> 
<li> Promover de conciertos independiente</li> 
<li> Intereses bancarios por tenencia de dinero en efectivo hasta después del evento</li>
</ul>
'; $lang['ul classalphalist                            lilicense to private schools amp learning institutionsli                            lidonate to the public school system gain publicity and intimate access to the youth market along with tax deductions from donationli                        ul'] = '<ul class=\'alphalist\'> 
<li>Licencia para los colegios públicos y privados</li> 
<li>Donar el sistema para la educación pública y privada, aumentar la publicidad y el acceso al mercado joven con las deducciones de impuestos por donaciones.</li>
</ul>'; $lang['ul classcompetitorlist                            lia hrefhttpwwwschoolnewspapersonlinecompricing targetblankschoolnewspaperonlinecompricinga  600  3900 usd  yearli                            lia hrefhttpwwwyourstudentnewscomarticlephpid8 targetblankyourstudentnewscoma  25  400 usd  yearli                            lia hrefhttpwwwihighcomadvertising targetblankihighcoma  advertising modelli                            lia hrefhttpswikispacescom targetblankwikispacescoma  freeli                            lia hrefhttpswwwedmodocom targetblankedmodocoma  freeli                            lia hrefhttpsgrockitcom targetblankgrockitcoma standardized test preparation  2999month li                        ul                                 a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesmeansresearchsnojpg datafancyboxgroupthemeans                             img srcwwwrootimagessitesmeansresearchsno400x0jpg                             div classblackoutfadebgdiv                        a                        a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesmeansresearchihighjpg datafancyboxgroupthemeans                             img srcwwwrootimagessitesmeansresearchihigh400x0jpg                             div classblackoutfadebgdiv                        a                                                a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesmeansresearchysnjpg datafancyboxgroupthemeans                             img srcwwwrootimagessitesmeansresearchysn400x0jpg                             div classblackoutfadebgdiv                        a'] = '<ul class=\'competitorlist\'>
                            <li><a href="http://www.schoolnewspapersonline.com/pricing/" target="_blank">SchoolNewsPaperOnline.com/pricing</a> - $600 - $3,900 USD / año</li>
                            <li><a href="http://www.yourstudentnews.com/article.php?id=8" target="_blank">YourStudentNews.com</a> - $25 - $400 USD / año</li>
                            <li><a href="http://www.ihigh.com/advertising/" target="_blank">iHigh.com</a> - modelo de publicidad</li>
                            <li><a href="https://wikispaces.com/" target="_blank">wikispaces.com</a> - gratis</li>
                            <li><a href="https://www.edmodo.com/" target="_blank">edmodo.com</a> - gratis</li>
                            <li><a href="https://grockit.com/" target="_blank">grockit.com</a> preparación de la prueba estandarizada - $29.99/mes</li>
                        </ul>         
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/means/research/sno.jpg" data-fancybox-group="themeans" >
                            <img src="/wwwroot/images/sites/means/research/sno_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/means/research/ihigh.jpg" data-fancybox-group="themeans" >
                            <img src="/wwwroot/images/sites/means/research/ihigh_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>                        
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/means/research/ysn.jpg" data-fancybox-group="themeans" >
                            <img src="/wwwroot/images/sites/means/research/ysn_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>'; $lang['ul classcompetitorlist                            lia targetblank hrefhttpswwwnolocomproductsjointownershipagreementforaninventionpr27213364htmlnolo pressa joint ownership agreement for an invention  3499 usd online form and wizardli                            lia targetblank hrefhttpswwwnolocomproductsintellectualpropertynolo pressa intellectual property books 20  20000 usdli                            lia targetblank hrefhttpwwwamazoncombestsellersbooksbusinesscontractslawzgbsbooks10824amazonsa most popular contract books  20  200 usdli                            lia hrefhttpwwwpollstarprocomopencontentaspxarticleid14194idhomesourcead targetblankpollstara subscriptions  400  800 usdli                            lia hrefhttpswwwlegalzoomcomlegalformsbandpartnershipagreement targetblanklegalzooma band partnership agreement  2999 usdli                        ul                        a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesaeresearchamazonmostpopularcontractsjpg datafancyboxgroupthemeans                             img srcwwwrootimagessitesaeresearchamazonmostpopularcontracts400x0jpg                             div classblackoutfadebgdiv                        a                        a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesaeresearchnolojointventureonlinejpg datafancyboxgroupthemeans                             img datasrc srcwwwrootimagessitesaeresearchnolojointventureonline400x0jpg                             div classblackoutfadebgdiv                        a'] = '<ul class=\'competitorlist\'>
                            <li><a target="_blank" href="https://www.nolo.com/products/joint-ownership-agreement-for-an-invention-pr272-13364.html/">Nolo Press</a> Acuerdo de Propiedad Conjunta para una invención, formulario interactivo y asistente - $ 34.99 USD </li>
                            <li><a target="_blank" href="https://www.nolo.com/products/intellectual-property">Nolo Press</a> Libros de Propiedad Intelectual $20 - $200.00 USD</li>
                            <li><a target="_blank" href="http://www.amazon.com/Best-Sellers-Books-Business-Contracts-Law/zgbs/books/10824">Amazon</a> mayoría de los libros de contrato populares - $20 - $200 USD</li>
                            <li><a href=\'http://www.pollstarpro.com/opencontent.aspx?ArticleID=14194&id=home&source=AD\' target=\'_blank\'>Pollstar</a> suscripciones - $400 - $800 USD</li>
                            <li><a href="https://www.legalzoom.com/legalforms/band-partnership-agreement" target=\'_blank\'>LegalZoom</a> Acuerdo de Asociación Banda - $29.99 USD</li>
                        </ul>
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ae/research/amazon-most-popular-contracts.jpg" data-fancybox-group="themeans" >
                            <img src="/wwwroot/images/sites/ae/research/amazon-most-popular-contracts_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ae/research/nolo-joint-venture-online.jpg" data-fancybox-group="themeans" >
                            <img data-src="" src="/wwwroot/images/sites/ae/research/nolo-joint-venture-online_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>'; $lang['ul classdatelist                            li6 months in 2 schools with basic texteditor and version controllingli                            li1 year in schools with fullfeature texteditor and multiuser version controllingli                        ul'] = '                          <ul class=\'datelist\'>
                            <li>6 meses: en 2 colegios con editor basico de texto y la versión controlar</li>
                            <li>1 año: afinar editor y tener una herramienta para que los profesores para editar documentos con un lápiz en un iPad</li>
                        </ul>'; $lang['ul classdatelist                            li6 months mobile app amp site completeli                        ul'] = '<ul class=\'datelist\'>
                            <li>6 meses: aplicación móvil y el sitio completo</li>
                        </ul>'; $lang['ul classdatelist                            li6 months virtual marketplace with promotional builder and searchpublishing by gps locationli                            li1 year in malls with maps and directory listingsli                        ul'] = '<ul class=\'datelist\'>
                            <li>6 meses: mercado virtual de promociones y búsqueda/publicación por ubicación GPS </li>
                            <li>1 año: en los centros comerciales con mapas y listado de directorio </li>
                        </ul>'; $lang['ul classdatelist                           li1 year mobile  site 5 interactive online contracts templates li                           li15 years contract wizard engine completeli                           li2 years selling in schoolsli                        ul'] = '<ul class=\'datelist\'>
                           <li>1 año: Sitio y móvil: 5 plantilla interactivos de contractos </li>
                           <li>1.5 años: contract wizard engine complete</li>
                           <li>2 años: ventas en las escuelas</li>
                        </ul>'; $lang['ul classdatelist                           li6  months mobile app site completeli                        ul'] = '<ul class=\'datelist\'>
                           <li>6 meses: aplicación móvil y el sitio completo</li>
                        </ul>'; $lang['ul classexpenselist                            li10 designli                            li40 developmentli                            li20 legalli                            li20 salesli                            li10 interviews  endorsementsli                        ul'] = '<ul class=\'expenselist\'>
                            <li>10% diseño</li>
                            <li>40% desarrollo</li>
                            <li>20% legal</li>
                            <li>20% ventas</li>
                            <li>10% entrevistas / endosos</li>
                        </ul>'; $lang['ul classexpenselist                            li15 designli                            li50 developmentli                            li25 salesli                            li10 hardwareli                        ul'] = '<ul class=\'expenselist\'>
                            <li>15% diseño</li>
                            <li>50% desarrollo</li>
                            <li>25% ventas</li>
                            <li>10% hardware</li>
                        </ul>'; $lang['ul classexpenselist                            li15 designli                            li70 developmentli                            li10 salesli                            li5 accountingli                            li5 legalli                        ul'] = '<ul class=\'expenselist\'>
                            <li>15% diseño</li>
                            <li>70% desarrollo</li>
                            <li>10% ventas</li>
                            <li>5%
contabilidad</li>
                            <li>5% legal</li>
                        </ul>'; $lang['ul classexpenselist                            li20 designli                            li60 developmentli                            li20 sales  supportli                        ul'] = '<ul class=\'expenselist\'>
                            <li>20% diseño</li>
                            <li>60% desarrollo</li>
                            <li>20% venta y soporte</li>
                        </ul>'; $lang['ul classexpenselist                            li30 designli                            li70 developmentli                        ul'] = '<ul class=\'expenselist\'>
                            <li>30% diseño</li>
                            <li>70% desarrollo</li>
                        </ul>'; $lang['ul classmarketresearch                            lia classsourcelink hrefhttpmoneyfutureofmusicorghowmanymusiciansarethere targetblankpollstara lists 10859 touring artists 71823 eventsli                            li815000 artists selfregistered on a hrefhttpmusicbrainzorgstatistics targetblankmusicbrainzorgali                            lia classsourcelink hrefhttpwwwascapcomabout targetblankascapa 435000 composters songwriters music publishersli                            lia classsourcelink hrefhttpwwwbmicomabout targetblankbmia 500000 composters songwriters music publishersli                                                    ul'] = '<ul class=\'marketresearch\'>
<li><a class=\'sourceLink\' href="http://money.futureofmusic.org/how-many-musicians-are-there/" target="_blank">Pollstar</a> dice que en 2012 habría 10.859 artistas en giras y 71.823 eventos</li>
<li>815.000 artistas se registraron en <a href="http://musicbrainz.org/statistics" target=\'_blank\'>musicbrainz.org</a></li>
<li><a class=\'sourceLink\' href="http://www.ascap.com/about/" target="_blank">ASCAP</a>: tienen 435,000 compostadores, compositores, editores de música</li>
<li><a class=\'sourceLink\' href="http://www.bmi.com/about" target="_blank">BMI</a>: tienen 500,000 compostadores, compositores, editores de música</li>                            
                        </ul>'; $lang['ul classmarketresearch                            liacross the united states there are 26407 public secondary schools and 10693 private secondary schools 2001  a hrefhttpwww2edgovaboutofficeslistovaepihshsfactshtml targetblanksourceali                            lithe total 1999 fall enrollment in public secondary schools grades 912 was slightly over 13369000 students 2001  a hrefhttpwww2edgovaboutofficeslistovaepihshsfactshtml targetblanksourceali                            lithere are 8262 secondary schools in colombia 2001  a hrefhttpwwwbdigitalunaleduco36671515indicadoresdegestic3b3nlosindicadoresdelalc3adneaobjetivo04dpdf targetblanksourceali                        ul'] = '<ul class=\'marketresearch\'>
                            <li>En todo Estados Unidos hay 26.407 escuelas secundarias públicas y 10.693 escuelas secundarias privadas (2001) - <a href="http://www2.ed.gov/about/offices/list/ovae/pi/hs/hsfacts.html" target="_blank">source</a></li>
                            <li>La matrícula total en 1999 en las escuelas secundarias públicas (grados 9-12) fue de poco encima de 13,369,000 de estudiantes (2001) - <a href="http://www2.ed.gov/about/offices/list/ovae/pi/hs/hsfacts.html" target="_blank">source</a></li>
                            <li>Hay 8,262 colegios en Colombia (2001) - <a href="http://www.bdigital.unal.edu.co/3667/15/15_Indicadores_de_Gesti%C3%B3n_los_indicadores_de_la_l%C3%ADnea_objetivo_04_D.PDF" target="_blank">source</a></li>
                        </ul>'; $lang['ul classmarketresearch                            lino online concert ticket vendors also support extensive music stations or playlistsli                            liconcert ticket sold 52 million 2011  a classsourcelink hrefhttpwwwstatisticbraincomconcertticketsalestatistics targetblanksourceali                            liconcert ticket revenue 31 billion usd 2011  a classsourcelink hrefhttpwwwstatisticbraincomconcertticketsalestatistics targetblanksourceali                            lipollstar lists 10859 touring artists 71823 events  a classsourcelink hrefhttpmoneyfutureofmusicorghowmanymusiciansarethere targetblanksourceali                            lia hrefhttpmusicbrainzorgstatistics targetblankmusicbrainzorgstatisticsali                            lia classsourcelink hrefhttpwwwascapcomabout targetblankascapa 435000 composters songwriters music publishersli                            lia classsourcelink hrefhttpwwwbmicomabout targetblankbmia 500000 composters songwriters music publishersli                                                    ul'] = '<ul class=\'marketresearch\'>

<li>No proveedores de billetes conciertos también tienen estaciones de música ni listas de reproducción</li>

<li>Boletas vendido: 52 million (2011 en EE.UU) - <a class=\'sourceLink\' href="http://www.statisticbrain.com/concert-ticket-sale-statistics/" target="_blank">source</a></li>

<li>Ingresa bruta de boletas vendido: 3.1 Billion USD (2011 en EE.UU) - <a class=\'sourceLink\' href="http://www.statisticbrain.com/concert-ticket-sale-statistics/" target="_blank">source</a></li>

<li><a class=\'sourceLink\' href="http://money.futureofmusic.org/how-many-musicians-are-there/" target="_blank">Pollstar</a> dice que en 2012 habría 10.859 artistas en giras y 71.823 eventos</li>

<li>815.000 artistas se registraron en <a href="http://musicbrainz.org/statistics" target=\'_blank\'>musicbrainz.org</a></li>

<li><a class=\'sourceLink\' href="http://www.ascap.com/about/" target="_blank">ASCAP</a>: tienen 435,000 compostadores, compositores, editores de música</li>

<li><a class=\'sourceLink\' href="http://www.bmi.com/about" target="_blank">BMI</a>: tienen 500,000 compostadores, compositores, editores de música</li> 

</ul>'; $lang['analytics'] = 'Analíticas'; $lang['any status'] = 'cualquier estado'; $lang['any type'] = 'cualquier tipo'; $lang['are you'] = 'tu eres'; $lang['art'] = 'Arte'; $lang['author'] = 'autor'; $lang['brands'] = 'Marcas'; $lang['business model'] = 'Modelo de Negocio'; $lang['client'] = 'cliente'; $lang['companies'] = 'empresas'; $lang['competition'] = 'competencia'; $lang['copyright'] = 'derechos de autor'; $lang['costs by department'] = 'costos por departamento'; $lang['debug'] = 'depurar'; $lang['deleted'] = 'Borrado'; $lang['dev'] = 'Desarrollo'; $lang['development'] = 'desarrollo'; $lang['e-learning'] = 'aprendizaje virtual'; $lang['ecommerce'] = 'comercio electronico'; $lang['edited'] = 'editado'; $lang['education'] = 'educación'; $lang['espaÃ±ol'] = 'español'; $lang['events'] = 'eventos'; $lang['fashion'] = 'modo'; $lang['file'] = 'archivo'; $lang['filters'] = 'filtros'; $lang['food'] = 'comida'; $lang['gaming'] = 'juegos'; $lang['health'] = 'salud'; $lang['import'] = 'importar'; $lang['industries'] = 'industrias'; $lang['key'] = 'clave'; $lang['kids'] = 'niños'; $lang['language'] = 'idioma'; $lang['last used'] = 'último uso'; $lang['lasted'] = 'Hasta'; $lang['launched'] = 'Lanzado'; $lang['launched/lasted:'] = 'lanzado/hasta'; $lang['license'] = 'licencia'; $lang['line'] = 'línea'; $lang['live'] = 'en vivo'; $lang['login'] = 'acceder'; $lang['logout'] = 'salir'; $lang['marketing'] = 'mercadeo'; $lang['messages'] = 'mensajes'; $lang['more images'] = 'más imágenes'; $lang['music'] = 'música'; $lang['no groupings'] = 'no hay agregaciones'; $lang['nothing changed'] = 'nada cambió'; $lang['of'] = 'de'; $lang['other'] = 'otro'; $lang['pics'] = 'fotos'; $lang['product deck'] = 'baraja de productos'; $lang['projects'] = 'proyectos'; $lang['propername'] = 'Nombres Propios'; $lang['publish'] = 'publicar'; $lang['research'] = 'investigar'; $lang['roadmap'] = 'plan &amp; horario'; $lang['roles'] = 'cargos'; $lang['row'] = 'fila'; $lang['settings'] = 'ajuste'; $lang['sports'] = 'deportes'; $lang['started:'] = 'inciado'; $lang['status'] = 'estado'; $lang['success'] = 'éxito'; $lang['tags'] = 'Etiquetas'; $lang['target markets'] = 'mercados objetivo'; $lang['team'] = 'equipo'; $lang['technologies'] = 'tecnologías'; $lang['tools'] = 'herramientas'; $lang['tutorial'] = 'tutoría'; $lang['unknown'] = 'desconocido'; $lang['update'] = 'actualizar'; $lang['updated'] = 'actualizado'; $lang['user generated content'] = 'contenido generado por el usuario'; $lang['years'] = 'años'; 
