<?php $lang['a classsnapshots mask0x250 fancybox hrefwwwrootimagessiteslealtadresearchandroidappsloyaltycardjpg datafancyboxgrouplealtadcard                             img srcwwwrootimagessiteslealtadresearchandroidappsloyaltycard400x0jpg                             div classblackoutfadebgdiv                        a                        a classsnapshots mask0x250 fancybox hrefwwwrootimagessiteslealtadresearchcitypointsjpg datafancyboxgrouplealtadcard                             img srcwwwrootimagessiteslealtadresearchcitypoints400x0jpg                             div classblackoutfadebgdiv                        a'] = '<a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/lealtad/research/android-apps-loyalty-card.jpg" data-fancybox-group="lealtadcard" >
                            <img src="/wwwroot/images/sites/lealtad/research/android-apps-loyalty-card_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/lealtad/research/citypoints.jpg" data-fancybox-group="lealtadcard" >
                            <img src="/wwwroot/images/sites/lealtad/research/citypoints_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>'; $lang['a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesstudioenvivoresearchandroidappelectrumdrummachinesamplerjpg datafancyboxgroupstudioenvivo                             img srcwwwrootimagessitesstudioenvivoresearchandroidappelectrumdrummachinesampler400x0jpg                             div classblackoutfadebgdiv                        a                        a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesstudioenvivoresearchandroidappdrummachinejpg datafancyboxgroupstudioenvivo                             img srcwwwrootimagessitesstudioenvivoresearchandroidappdrummachine400x0jpg                             div classblackoutfadebgdiv                        a'] = '<a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/studioenvivo/research/android-app-electrum-drum-machine-sampler.jpg" data-fancybox-group="studioenvivo" >
                            <img src="/wwwroot/images/sites/studioenvivo/research/android-app-electrum-drum-machine-sampler_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/studioenvivo/research/android-app-drum-machine.jpg" data-fancybox-group="studioenvivo" >
                            <img src="/wwwroot/images/sites/studioenvivo/research/android-app-drum-machine_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>'; $lang['a classsnapshots mask0x250 fancybox hrefwwwrootimagessitestaresearchandroidappsmusicgamesjpg datafancyboxgrouptrackauthority                             img srcwwwrootimagessitestaresearchandroidappsmusicgames400x0jpg                             div classblackoutfadebgdiv                        a'] = '<ul class=\'competitorlist\'>
<li><a href="http://www.pandora.com" target="_blank">Pandora.com</a> Free, $39/year ad-free</li>

<li><a href="http://www.spotify.com" target="_blank">Spotify.com</a> Free, $5/month ad-free, $10/month ad-free with off-line mobile access</li>

</ul> 

<a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ta/research/android-apps-music-games.jpg" data-fancybox-group="trackauthority" >
<img src="/wwwroot/images/sites/ta/research/android-apps-music-games_400x0.jpg" />
<div class="blackOutFadeBG"></div>
</a>

<a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ta/research/vivetuboleta.jpg" data-fancybox-group="trackauthority" >
<img src="/wwwroot/images/sites/ta/research/vivetuboleta_400x0.jpg" />
<div class="blackOutFadeBG"></div>
</a>

<a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ta/research/ticket-express.jpg" data-fancybox-group="trackauthority" >
<img src="/wwwroot/images/sites/ta/research/ticket-express_400x0.jpg" />
<div class="blackOutFadeBG"></div>
</a>

<a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ta/research/entradas-y-conciertos.jpg" data-fancybox-group="trackauthority" >
<img src="/wwwroot/images/sites/ta/research/entradas-y-conciertos_400x0.jpg" />
<div class="blackOutFadeBG"></div>
</a>'; $lang['ema platform for high school newspapers that allows students to collaborate and share their academic and athletic achievementsem                pstudents and teachers would be able to develop assignments work on multiple versions of a story share ideas within the class and morep                            pthe competitive advantage of this site is in the versioncontrolling system that allows peerreviews teachers edit and the students versions to all be tracked independently in addition the system would include tools for simplifying footnotes and sources and to include photos and linksp'] = '<em>A platform for High School newspapers that allows students to collaborate and share their academic and athletic achievements.</em>

<p>Students and teachers will be able to develop assignments, work on multiple versions of a story, share ideas within the class, and more.</p>            

<p>The competitive advantage of this site is in the version-controlling system that allows peer-reviews, teachers\' edits, and the students\' versions to all be tracked independently. Teachers will be able to markup and grade student essays with a iPad and stylus by writing on the screen</p>'; $lang['ema virtual marketplace for independent retailers to publish and track promotions along with their returnoninvestment roiem                    pcustomers can search promotions and publish their own requests to nearby retailers for special deals the marketplace is focused on private offers only valid for a few hoursp'] = '<em>A virtual marketplace for independent retailers to publish and track promotions, along with their return-on-investment (ROI).</em>
                    <p>Customers can search promotions and publish their own requests to nearby retailers for special deals. The marketplace is focused on private offers only valid for a few hours.</p>'; $lang['eman etextbook for the legal and strategical aspects of the music recording industryem                      pthe tool would guide and prepare artists concert promoters event venues and talent managers through business and contract negotiations for a wide variety of agreements p                      pthe interactive questionnaire would include videos podcasts and written advice from experienced prominent attorneys artists managers and other industry professionalsp'] = '<em>An e-Textbook for the Legal and Strategic Aspects of the Music Recording Industry.</em>
<p>The tool will prepare and assist artists, promoters, venues, and managers and dealmakers through business and contract negotiations for a wide variety of agreements.</p>
<p>The interactive questionnaire will include videos, podcasts, and written advice from experienced, prominent attorneys and other industry professionals.</p>'; $lang['eman online and mobile game for music lovers to play exchange and reward musical tasteem                    phighly rated users are rewarded with free music gift certificates concert tickets and cash from sponsors and partnersp                    pthe platform supports three ways to play and win each starts with a playlist theme such as rise and shine songs for my alarm clockp                    ul                        li1 group members enter a song that suits the themeli                        li2 group members list and rate each others songsli                        li3 after two weeks the person who submitted the highest rated song winsli                    ul                    pthis game can easily be incorporated as a promotional vehicle for concert tours for example if that alarm clock was jayzs the options are countless for prizes from tickets to backstage passes and all links during the competition promote the concertp'] = '<em>An online and mobile game for music lovers to play, exchange, and reward musical taste.</em>
                    <p>Highly rated users are rewarded with free music, gift certificates, concert tickets and cash from sponsors and partners.</p>
                    <p>The platform supports three ways to play and win. Each starts with a playlist theme, and all three have unique way to promote artists, music videos, and concert tours.</p>'; $lang['emthe first mobile beat machine to create and share music with friends in realtimeem                     plike most similar apps studioenvivo allows customizing your keyboard with sounds and laying background tracks as you playp                    phowever unlike any other app you can play simultaneously with other friends via bluetooth  chord  allshare frameworks and finally stitch together your recordings for a collaborative compositionp                    pas users upload their compositions to the cloud the social aspect of sharing and comparing compositions are endlessp'] = '<em>The first mobile beat machine to create and share music with friends in real-time.</em> 
                    <p>Like most similar apps, StudioEnVivo allows customizing your keyboard with sounds and laying background tracks as you play.</p>
                    <p>However, unlike any other app, you can play simultaneously with other friends via Bluetooth / Chord / All-Share frameworks and finally stitch together your recordings for a collaborative composition.</p>
                    <p>As users upload their compositions to the cloud, the social aspect of sharing and comparing compositions are endless...</p>'; $lang['peli founded taylor made management in 2002 to produce a public music amp arts festival called a hrefprojectspid7 targetblanktraffica this url was the a hrefhttptraffictaylormadetrafficcomtraffichtml targetblankwebsitea today it is a portfolio of the projects he has been blessed to be part of and the many a hrefteampeoplea who have contributedppthis page features the products and brands directly from taylormadetraffic we are seeking likeminded visionaries that know how to develop design or sell if thats you please reach out span classalinktmttaylormadetrafficcomspanppif you have your own product that you are passionate about and feel i might be of service please do the same or use the filters above to find similar work experiences by a hreftechnologiestechnologya or a hrefindustriesindustryap'] = '<p>Eli founded Taylor Made Management in 2002 to produce a public music & arts festival called <a href=\'/projects?pid=7\' target=\'_blank\'>Traffic</a>. This URL was the <a href=\'http://traffic.taylormadetraffic.com/traffic.html\' target=\'_blank\'>website</a>. Today it is a portfolio of the projects he has been blessed to be part of and the many <a href="/team">people</a> who have contributed.</p>

<p>This page features the products and brands directly from TaylorMadeTraffic. We are seeking like-minded visionaries that know how to develop, design or sell. If that\'s you, please reach out: <span class=\'alink\'>tmt@taylormadetraffic.com</span></p>

<p>If you have your own product that you are passionate about, and feel I might be of service, please do the same or use the filters above to find similar work experiences by <a href=\'/technologies\'>technology</a> or <a href=\'/industries\'>industry</a></p>'; $lang['pi am looking for the right team to share these vision and expand the businessppif you are interested in one from this short summary please request the complete media kit and business plan each has a much more indepth analysis of the target market industry competitors technical hurdles and business models and opportunitiesp'] = '<p>I am looking for the right team to share these visions and expand its business. If you see potential in one from these short summaries, please request its complete media kit and business plan.</p>

<p>Each product has reports with a much more in-depth analysis of the target markets, industry competitors, technical hurdles, and business models and opportunities to grow.</p>'; $lang['pi am searching for the perfect international team to share these vision and expand the business if you are interested in a product from one of these short summaries please request the complete media kit and business plan each has a much more indepth analysis of the target market industry competitors technical hurdles and profitable opportunitiesp'] = '<p>I want to bring together the perfect international team of entrepreneurs, developers, and designs to share these vision and expand their business models. This page only shows very short summaries on 5 ideas. Email me to request a complete business plan on any one with a more in-depth analysis of the target market, industry competitors, technical hurdles, and profitable opportunities.</p>'; $lang['pi have a passion for music art culture and education to diversify my exposure and knowledge of those subjects i live between san francisco california bogot colombia and the hawaiian island of kauaippcombined with skills in an array of computer technologies as well as broad experiences in business development my focus is helping companies develop their own systems and finding strategies for expansion throughout south americappwhere ever you are in the world if you have a product you are also passionate about and feel i could be of service i love a good excuse to travel and will generally assume the cost for serious inquiries to do so i am always available via email span classalinkeattaylormadetrafficcomspan google voice span classalink14153000834span or skype span classalinkskyeelispanp'] = '<p>I have a passion for music, art, culture and education. To diversify my exposure and knowledge of these, I live between San Francisco, California, Bogotá, Colombia, and the Hawaiian Island of Kauai.</p>

<p>Combined with skills in an array of computer technologies as well as broad experiences in business development, my focus is helping companies develop their own systems and finding strategies for expansion throughout South America.</p>

<p>Wherever you are in the world, If you have a product you are also passionate about and feel I could be of service, I love a good excuse to travel and will generally assume the cost for serious inquiries. To do so, I am always available via email: <span class=\'alink\'>eli@taylormadetraffic.com</span>, google voice: <span class=\'alink\'>1-415-300-0834</span> or, skype: <span class=\'alink\'>skye_eli</span></p>'; $lang['ul classalphalist                            li1 download adfree versionli                            li5 download adfree with offline access and cloud storageli                        ul'] = '<ul class=\'alphalist\'>
                            <li>$1 download ad-free version</li>
                            <li>$5 download ad-free with offline access and cloud storage</li>
                        </ul>'; $lang['ul classalphalist                            li1month for store owners to view customers data and analyticsli                            li1month for store owners to send 100 private discount offers per monthli                            li1month for store owners to public 10 public market ads per monthli                            lidesign amp development services for more engaging mobile ads and promotionsli                            libuild interactive and engaging maps for mallsli                        ul'] = '<ul class=\'alphalist\'>
                            <li>$1/month for store owners to view customers data and analytics</li>
                            <li>$1/month for store owners to send 100 private discount offers per month</li>
                            <li>$1/month for store owners to public 10 public market ads per month</li>
                            <li>Design & Development services for more engaging mobile ads and promotions</li>
                            <li>Build interactive and engaging maps for malls</li>
                        </ul>'; $lang['ul classalphalist                            li50 textbook sold through music and law institutions and universitiesli                            li10  50 online subscriptionsli                        ul'] = '<ul class=\'alphalist\'>
                            <li>$50 textbook sold through music and law institutions and universities</li>
                            <li>$10 - $50 online subscriptions.</li>
                        </ul>'; $lang['ul classalphalist                            liconcert ticket resales 35 feeli                            li1  10 subscriptions to adfree listening and extra playlist featuresli                            liconcert ticket promotions advertising and salesli                        ul'] = '<ul class=\'alphalist\'>
                            <li>concert ticket re-sales (3-5% fee)</li>
                            <li>$1 - $10 subscriptions to ad-free listening and extra playlist features</li>
                            <li>Concert ticket promotions, advertising and sales</li>
<li>Bank interest from holding cash until after event</li>
                        </ul>'; $lang['ul classalphalist                            lilicense to private schools amp learning institutionsli                            lidonate to the public school system gain publicity and intimate access to the youth market along with tax deductions from donationli                        ul'] = '<ul class=\'alphalist\'>
                            <li>License to private schools & learning institutions</li>
                            <li>Donate to the public school system, gain publicity and intimate access to the youth market, along with tax deductions from donation.</li>
                        </ul>'; $lang['ul classcompetitorlist                            lia hrefhttpwwwschoolnewspapersonlinecompricing targetblankschoolnewspaperonlinecompricinga  600  3900 usd  yearli                            lia hrefhttpwwwyourstudentnewscomarticlephpid8 targetblankyourstudentnewscoma  25  400 usd  yearli                            lia hrefhttpwwwihighcomadvertising targetblankihighcoma  advertising modelli                            lia hrefhttpswikispacescom targetblankwikispacescoma  freeli                            lia hrefhttpswwwedmodocom targetblankedmodocoma  freeli                            lia hrefhttpsgrockitcom targetblankgrockitcoma standardized test preparation  2999month li                        ul                                 a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesmeansresearchsnojpg datafancyboxgroupthemeans                             img srcwwwrootimagessitesmeansresearchsno400x0jpg                             div classblackoutfadebgdiv                        a                        a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesmeansresearchihighjpg datafancyboxgroupthemeans                             img srcwwwrootimagessitesmeansresearchihigh400x0jpg                             div classblackoutfadebgdiv                        a                                                a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesmeansresearchysnjpg datafancyboxgroupthemeans                             img srcwwwrootimagessitesmeansresearchysn400x0jpg                             div classblackoutfadebgdiv                        a'] = '<ul class=\'competitorlist\'>
                            <li><a href="http://www.schoolnewspapersonline.com/pricing/" target="_blank">SchoolNewsPaperOnline.com/pricing</a> - $600 - $3,900 USD / year</li>
                            <li><a href="http://www.yourstudentnews.com/article.php?id=8" target="_blank">YourStudentNews.com</a> - $25 - $400 USD / year</li>
                            <li><a href="http://www.ihigh.com/advertising/" target="_blank">iHigh.com</a> - advertising model</li>
                            <li><a href="https://wikispaces.com/" target="_blank">wikispaces.com</a> - free</li>
                            <li><a href="https://www.edmodo.com/" target="_blank">edmodo.com</a> - free</li>
                            <li><a href="https://grockit.com/" target="_blank">grockit.com</a> standardized test preparation - $29.99/month </li>
                        </ul>         
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/means/research/sno.jpg" data-fancybox-group="themeans" >
                            <img src="/wwwroot/images/sites/means/research/sno_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/means/research/ihigh.jpg" data-fancybox-group="themeans" >
                            <img src="/wwwroot/images/sites/means/research/ihigh_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>                        
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/means/research/ysn.jpg" data-fancybox-group="themeans" >
                            <img src="/wwwroot/images/sites/means/research/ysn_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>'; $lang['ul classcompetitorlist                            lia targetblank hrefhttpswwwnolocomproductsjointownershipagreementforaninventionpr27213364htmlnolo pressa joint ownership agreement for an invention  3499 usd online form and wizardli                            lia targetblank hrefhttpswwwnolocomproductsintellectualpropertynolo pressa intellectual property books 20  20000 usdli                            lia targetblank hrefhttpwwwamazoncombestsellersbooksbusinesscontractslawzgbsbooks10824amazonsa most popular contract books  20  200 usdli                            lia hrefhttpwwwpollstarprocomopencontentaspxarticleid14194idhomesourcead targetblankpollstara subscriptions  400  800 usdli                            lia hrefhttpswwwlegalzoomcomlegalformsbandpartnershipagreement targetblanklegalzooma band partnership agreement  2999 usdli                        ul                        a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesaeresearchamazonmostpopularcontractsjpg datafancyboxgroupthemeans                             img srcwwwrootimagessitesaeresearchamazonmostpopularcontracts400x0jpg                             div classblackoutfadebgdiv                        a                        a classsnapshots mask0x250 fancybox hrefwwwrootimagessitesaeresearchnolojointventureonlinejpg datafancyboxgroupthemeans                             img datasrc srcwwwrootimagessitesaeresearchnolojointventureonline400x0jpg                             div classblackoutfadebgdiv                        a'] = '<ul class=\'competitorlist\'>
                            <li><a target="_blank" href="https://www.nolo.com/products/joint-ownership-agreement-for-an-invention-pr272-13364.html/">Nolo Press</a> Joint Ownership Agreement for an Invention - $34.99 USD online form and wizard</li>
                            <li><a target="_blank" href="https://www.nolo.com/products/intellectual-property">Nolo Press</a> Intellectual Property Books $20 - $200.00 USD</li>
                            <li><a target="_blank" href="http://www.amazon.com/Best-Sellers-Books-Business-Contracts-Law/zgbs/books/10824">Amazon\'s</a> most popular contract books - $20 - $200 USD</li>
                            <li><a href=\'http://www.pollstarpro.com/opencontent.aspx?ArticleID=14194&id=home&source=AD\' target=\'_blank\'>Pollstar</a> subscriptions - $400 - $800 USD</li>
                            <li><a href="https://www.legalzoom.com/legalforms/band-partnership-agreement" target=\'_blank\'>LegalZoom</a> Band Partnership Agreement - $29.99 USD</li>
                        </ul>
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ae/research/amazon-most-popular-contracts.jpg" data-fancybox-group="themeans" >
                            <img src="/wwwroot/images/sites/ae/research/amazon-most-popular-contracts_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>
                        <a class="snapshots mask0x250 fancybox" href="/wwwroot/images/sites/ae/research/nolo-joint-venture-online.jpg" data-fancybox-group="themeans" >
                            <img data-src="" src="/wwwroot/images/sites/ae/research/nolo-joint-venture-online_400x0.jpg" />
                            <div class="blackOutFadeBG"></div>
                        </a>'; $lang['ul classdatelist                            li6 months in 2 schools with basic texteditor and version controllingli                            li1 year in schools with fullfeature texteditor and multiuser version controllingli                        ul'] = '<ul class=\'datelist\'>
                            <li>6 months: in 2 schools with basic text-editor and version controlling</li>
                            <li>1 year: fine tude the text-editor and have a tool for teachers to mark-up and grade student papers with a stylus in an iPad</li>
                        </ul>'; $lang['ul classdatelist                            li6 months mobile app amp site completeli                        ul'] = '<ul class=\'datelist\'>
                            <li>6 months: mobile app & site complete</li>
                        </ul>'; $lang['ul classdatelist                            li6 months virtual marketplace with promotional builder and searchpublishing by gps locationli                            li1 year in malls with maps and directory listingsli                        ul'] = '<ul class=\'datelist\'>
                            <li>6 months: virtual marketplace with promotional builder and search/publishing by GPS location</li>
                            <li>1 year: in malls with maps and directory listings</li>
                        </ul>'; $lang['ul classdatelist                           li1 year mobile  site 5 interactive online contracts templates li                           li15 years contract wizard engine completeli                           li2 years selling in schoolsli                        ul'] = '<ul class=\'datelist\'>
                           <li>1 year: mobile & site: 5 interactive, online contracts templates </li>
                           <li>1.5 years: contract wizard engine complete</li>
                           <li>2 years: selling in schools</li>
                        </ul>'; $lang['ul classdatelist                           li6  months mobile app site completeli                        ul'] = '<ul class=\'datelist\'>
                           <li>6  months: mobile app and site complete</li>
                        </ul>'; $lang['ul classexpenselist                            li10 designli                            li40 developmentli                            li20 legalli                            li20 salesli                            li10 interviews  endorsementsli                        ul'] = '<ul class=\'expenselist\'>
                            <li>10% design</li>
                            <li>40% development</li>
                            <li>20% legal</li>
                            <li>20% sales</li>
                            <li>10% interviews / endorsements</li>
                        </ul>'; $lang['ul classexpenselist                            li15 designli                            li50 developmentli                            li25 salesli                            li10 hardwareli                        ul'] = '<ul class=\'expenselist\'>
                            <li>15% design</li>
                            <li>50% development</li>
                            <li>25% sales</li>
                            <li>10% hardware</li>
                        </ul>'; $lang['ul classexpenselist                            li15 designli                            li70 developmentli                            li10 salesli                            li5 accountingli                            li5 legalli                        ul'] = '<ul class=\'expenselist\'>
                            <li>15% design</li>
                            <li>70% development</li>
                            <li>10% sales</li>
                            <li>5% accounting</li>
                            <li>5% legal</li>
                        </ul>'; $lang['ul classexpenselist                            li20 designli                            li60 developmentli                            li20 sales  supportli                        ul'] = '<ul class=\'expenselist\'>
                            <li>20% design</li>
                            <li>60% development</li>
                            <li>20% sales & support</li>
                        </ul>'; $lang['ul classexpenselist                            li30 designli                            li70 developmentli                        ul'] = '<ul class=\'expenselist\'>
                            <li>30% design</li>
                            <li>70% development</li>
                        </ul>'; $lang['ul classmarketresearch                            lia classsourcelink hrefhttpmoneyfutureofmusicorghowmanymusiciansarethere targetblankpollstara lists 10859 touring artists 71823 eventsli                            li815000 artists selfregistered on a hrefhttpmusicbrainzorgstatistics targetblankmusicbrainzorgali                            lia classsourcelink hrefhttpwwwascapcomabout targetblankascapa 435000 composters songwriters music publishersli                            lia classsourcelink hrefhttpwwwbmicomabout targetblankbmia 500000 composters songwriters music publishersli                                                    ul'] = '<ul class=\'marketresearch\'>
                            <li><a class=\'sourceLink\' href="http://money.futureofmusic.org/how-many-musicians-are-there/" target="_blank">Pollstar</a> lists 10,859 touring artists, 71,823 Events</li>
                            <li>815,000 artists self-registered on <a href="http://musicbrainz.org/statistics" target=\'_blank\'>musicbrainz.org</a></li>
                            <li><a class=\'sourceLink\' href="http://www.ascap.com/about/" target="_blank">ASCAP</a>: 435,000 composters, songwriters, music publishers</li>
                            <li><a class=\'sourceLink\' href="http://www.bmi.com/about" target="_blank">BMI</a>: 500,000 composters, songwriters, music publishers</li>                            
                        </ul>'; $lang['ul classmarketresearch                            liacross the united states there are 26407 public secondary schools and 10693 private secondary schools 2001  a hrefhttpwww2edgovaboutofficeslistovaepihshsfactshtml targetblanksourceali                            lithe total 1999 fall enrollment in public secondary schools grades 912 was slightly over 13369000 students 2001  a hrefhttpwww2edgovaboutofficeslistovaepihshsfactshtml targetblanksourceali                            lithere are 8262 secondary schools in colombia 2001  a hrefhttpwwwbdigitalunaleduco36671515indicadoresdegestic3b3nlosindicadoresdelalc3adneaobjetivo04dpdf targetblanksourceali                        ul'] = '<ul class=\'marketresearch\'>
                            <li>Across the United States there are 26,407 public secondary schools and 10,693 private secondary schools (2001) - <a href="http://www2.ed.gov/about/offices/list/ovae/pi/hs/hsfacts.html" target="_blank">source</a></li>
                            <li>The total 1999 fall enrollment in public secondary schools (grades 9-12) was slightly over 13,369,000 students (2001) - <a href="http://www2.ed.gov/about/offices/list/ovae/pi/hs/hsfacts.html" target="_blank">source</a></li>
                            <li>There are 8,262 secondary schools in Colombia (2001) - <a href="http://www.bdigital.unal.edu.co/3667/15/15_Indicadores_de_Gesti%C3%B3n_los_indicadores_de_la_l%C3%ADnea_objetivo_04_D.PDF" target="_blank">source</a></li>
                        </ul>'; $lang['ul classmarketresearch                            lino online concert ticket vendors also support extensive music stations or playlistsli                            liconcert ticket sold 52 million 2011  a classsourcelink hrefhttpwwwstatisticbraincomconcertticketsalestatistics targetblanksourceali                            liconcert ticket revenue 31 billion usd 2011  a classsourcelink hrefhttpwwwstatisticbraincomconcertticketsalestatistics targetblanksourceali                            lipollstar lists 10859 touring artists 71823 events  a classsourcelink hrefhttpmoneyfutureofmusicorghowmanymusiciansarethere targetblanksourceali                            lia hrefhttpmusicbrainzorgstatistics targetblankmusicbrainzorgstatisticsali                            lia classsourcelink hrefhttpwwwascapcomabout targetblankascapa 435000 composters songwriters music publishersli                            lia classsourcelink hrefhttpwwwbmicomabout targetblankbmia 500000 composters songwriters music publishersli                                                    ul'] = '<ul class=\'marketresearch\'>
                            <li>NO online concert ticket vendors also support extensive music stations or playlists</li>
                            <li>Concert Ticket sold 52 million (2011) - <a class=\'sourceLink\' href="http://www.statisticbrain.com/concert-ticket-sale-statistics/" target="_blank">source</a></li>
                            <li>Concert Ticket Revenue 3.1 Billion USD (2011) - <a class=\'sourceLink\' href="http://www.statisticbrain.com/concert-ticket-sale-statistics/" target="_blank">source</a></li>
                            <li>Pollstar lists 10,859 touring artists, 71,823 Events - <a class=\'sourceLink\' href="http://money.futureofmusic.org/how-many-musicians-are-there/" target="_blank">source</a></li>
                            <li><a href="http://musicbrainz.org/statistics" target=\'_blank\'>musicbrainz.org/statistics</a></li>
                            <li><a class=\'sourceLink\' href="http://www.ascap.com/about/" target="_blank">ASCAP</a>: 435,000 composters, songwriters, music publishers</li>
                            <li><a class=\'sourceLink\' href="http://www.bmi.com/about" target="_blank">BMI</a>: 500,000 composters, songwriters, music publishers</li>                            
                        </ul>'; $lang['analytics'] = 'Analytics'; $lang['art'] = 'Art'; $lang['cambiar idioma'] = 'change language'; $lang['cambiar todos campos'] = 'change all fields'; $lang['espaÃ±ol'] = 'español'; $lang['filas'] = 'rows'; $lang['propername'] = 'Proper Name'; $lang['siguente'] = 'next'; $lang['tags'] = 'Tags'; 
